name = "Ametrine"
description = "Elegant, pretty, and snappy Zola theme."
license = "MIT"
homepage = "https://codeberg.org/Geode/ametrine"
min_version = "0.19.0"
demo = "https://ametrine.daudix.one"

[author]
name = "David Lapshin"
homepage = "https://daudix.one"
